# list of policies to be executed for self healing
heron.class.health.policies:
  - failed-tuple-policy

# configuration specific to individual policies listed above
failed-tuple-policy:
  health.policy.class: "com.twitter.heron.healthmgr.policy.FailedTuplesPolicy"
  health.policy.interval.ms: "10000"
