# list of policies to be executed for self healing
heron.class.health.policies:
  - bp-tuple-policy

# configuration specific to individual policies listed above
bp-tuple-policy:
  health.policy.class: "com.twitter.heron.healthmgr.policy.BackPressurePolicy"
  health.policy.interval.ms: "10000"

throughput-sla-policy:
  health.policy.class: "com.twitter.heron.healthmgr.policy.ThroughputSLAPolicy"
  health.policy.throughput.sla.per.sec: "150000"